export const API_URL = process.env.NEXT_PUBLIC_API_URL;

export const API_ROUTES = {
  LOGIN: `${API_URL}/api/auth/login`,
  SIGNUP: `${API_URL}/api/auth/signup`,
  GET_COUNTRIES: `${API_URL}/api/static/countries`,
  GET_STATES: `${API_URL}/api/static/states`,
  GET_CITIES: `${API_URL}/api/static/cities`,
  ADD_UNIT: `${API_URL}/api/units`,
  GET_UNITS: `${API_URL}/api/units`,
  GET_UNIT_BY_ID: (id: string) => `${API_URL}/api/units/${id}`,
  CREATE_TENANCY: `${API_URL}/api/tenancies`,
  GET_TENANCIES: `${API_URL}/api/tenancies`,
  GET_TENANCY_BY_ID: (id: string) => `${API_URL}/api/tenancies/${id}`,
  UPDATE_USER: (id: string) => `${API_URL}/api/users/${id}`,
  GET_USER_BY_ID: (id: string) => `${API_URL}/api/users/${id}`,
  GET_USERS: `${API_URL}/api/users`,
  CREATE_AGREEMENT: `${API_URL}/api/agreements`,
  GET_AGREEMENTS: `${API_URL}/api/agreements`,
  GET_AGREEMENT_BY_ID: (id: string) => `${API_URL}/api/agreements/${id}`,
  SIGN_AGREEMENT: (id: string) => `${API_URL}/api/agreements/${id}/sign`,
  UPLOAD_IMAGE: `${API_URL}/api/upload/image`,
  UPLOAD_VIDEO: `${API_URL}/api/upload/video`,
  UPLOAD_DOCUMENT: `${API_URL}/api/upload/document`,
  UPLOAD_FILE: `${API_URL}/api/upload`,
  UPLOAD_MULTIPLE: `${API_URL}/api/upload/multiple`,
};
